# This file was generated by GoReleaser. DO NOT EDIT.
cask "castctl" do
  name "castctl"
  desc "CAST AI CLI"
  homepage "https://cast.ai"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "castctl"

  on_macos do
    on_intel do
      url "https://storage.googleapis.com/damian-castai-onboard/#{version}/castctl_darwin_amd64.tar.gz"
      sha256 "3e6942a4d1c3760ac63650280edc70f174293727ba2fea4796afe5f8649ecea4"
    end
    on_arm do
      url "https://storage.googleapis.com/damian-castai-onboard/#{version}/castctl_darwin_arm64.tar.gz"
      sha256 "48ef21a63bca3003472517c041bf222d3a03591bbd0bdc6e17dc5371102bdacb"
    end
  end

  on_linux do
    on_intel do
      url "https://storage.googleapis.com/damian-castai-onboard/#{version}/castctl_linux_amd64.tar.gz"
      sha256 "e6d09dfb604e9bb1a5c1a46557563b6c2eb7d632a3c06b6aaea77cb3e4b449c0"
    end
    on_arm do
      url "https://storage.googleapis.com/damian-castai-onboard/#{version}/castctl_linux_arm64.tar.gz"
      sha256 "480e969c4fc9150c1b066b624191709cc76c5d5181647f8fc1bc587a2b254d72"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/castctl"]
    end
  end

  # No zap stanza required
end
