# This file was generated by GoReleaser. DO NOT EDIT.
cask "castctl" do
  name "castctl"
  desc "CAST AI CLI"
  homepage "https://cast.ai"
  version "v0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "castctl"

  on_macos do
    on_intel do
      url "https://storage.googleapis.com/damian-castai-onboard/#{version}/castctl_darwin_amd64.tar.gz"
      sha256 "55dd157a708f5752f1884c1b4c2a09698c2c8d84a2e39b5b93858e9c3b82f73e"
    end
    on_arm do
      url "https://storage.googleapis.com/damian-castai-onboard/#{version}/castctl_darwin_arm64.tar.gz"
      sha256 "431c37c155c3bad0d52a80c596ce7f22c99e736968e7cf80df50259a63667029"
    end
  end

  on_linux do
    on_intel do
      url "https://storage.googleapis.com/damian-castai-onboard/#{version}/castctl_linux_amd64.tar.gz"
      sha256 "e87a1b81912b205266ba2f5f3145a09c89cbd2a2b6b8df377692b54ff4617fc5"
    end
    on_arm do
      url "https://storage.googleapis.com/damian-castai-onboard/#{version}/castctl_linux_arm64.tar.gz"
      sha256 "02c253e86c5efba95e29b43fbb897ed982872f6e28574d6bea7f64f2b5350431"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/castctl"]
    end
  end

  # No zap stanza required
end
