# This file was generated by GoReleaser. DO NOT EDIT.
cask "castctl" do
  name "castctl"
  desc "CAST AI CLI"
  homepage "https://cast.ai"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "castctl"

  on_macos do
    on_intel do
      url "https://storage.googleapis.com/damian-castai-onboard/#{version}/castctl_darwin_amd64.tar.gz"
      sha256 "14102f07907a9ad880facfd9212eae0205e520bacbb680b8a38f4bcc0f35c7d8"
    end
    on_arm do
      url "https://storage.googleapis.com/damian-castai-onboard/#{version}/castctl_darwin_arm64.tar.gz"
      sha256 "b7f5830781c90b16490e27ada0aa048eda942f34be42973d8eb66cfee6bc84ee"
    end
  end

  on_linux do
    on_intel do
      url "https://storage.googleapis.com/damian-castai-onboard/#{version}/castctl_linux_amd64.tar.gz"
      sha256 "567ae0f11b752e6549e46f28877313f20c7cc8acf503af46e809050ec184eff6"
    end
    on_arm do
      url "https://storage.googleapis.com/damian-castai-onboard/#{version}/castctl_linux_arm64.tar.gz"
      sha256 "470c24839be50513afd099d2d28afb8ae8054ec55f793cec83a4e385c9f87e42"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/castctl"]
    end
  end

  # No zap stanza required
end
